import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          .dm-serif.display-regular {
            font-family: "DM Serif Display", serif;
            font-weight: 400;
            font-style: normal;
          }

          .dm-serif.display-regular-italic {
            font-family: "DM Serif Display", serif;
            font-weight: 400;
            font-style: italic;
          }
        `}</style>
      </head>
      <body className={`${inter.className} dm-serif display-regular`}>
        {children}
      </body>
    </html>
  );
}
